version: '3.8'

services:
  assignit_frontend:
    image: node:20
    #build: .
    container_name: assignit_frontend
    working_dir: /app
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - "3191:5173"
    command: ["npm","start"]
