version: '3.8'

services:
  assignit_frontend:
    image: nginx
    #build: .
    container_name: assignit_frontend
    volumes:
      - ./dist:/usr/share/nginx/html
#      - ./:/app
    restart: unless-stopped
    ports:
      - 3191:80
#    command: ["npm","start"]
